### ISSUE TITLE
Unhandled NotImplementedError in onDetachedFromActivity of SmsRetrieverApiPlusPlugin.kt causes app crash

### ISSUE THREAD

**Issue by angatiabenson** [PanneerDev/sms_retrieve_api_plus#1]
I encountered a fatal exception with message 'An operation is not implemented: Not yet implemented' in SmsRetrieverApiPlusPlugin.onDetachedFromActivity at line 121, leading to app crash.

```
          Fatal Exception: x9.l: An operation is not implemented: Not yet implemented
       at com.sms.retriever.sms_retriever_api_plus.SmsRetrieverApiPlusPlugin.onDetachedFromActivity(SmsRetrieverApiPlusPlugin.kt:121)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:381)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:747)
       at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:1176)
       at androidx.fragment.app.Fragment.performDetach(Fragment.java:3387)
       at androidx.fragment.app.FragmentStateManager.detach(FragmentStateManager.java:862)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:355)
       at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete$fragment_release(SpecialEffectsController.kt:805)
       at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.kt:641)
       at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.kt:355)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3201)
       at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3152)
       at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
       at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:258)
       at android.app.Activity.performDestroy(Activity.java:9049)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1510)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5971)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:6022)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:185)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2643)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:257)
       at android.os.Looper.loop(Looper.java:368)
       at android.app.ActivityThread.main(ActivityThread.java:8839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
```

**Comment by abolfazlMKazemi** [comment]
i have this same bug

**Comment by PS-Developers** [comment]
issue fixed, thanks for supporting
